### PR TITLE
Fix where clauses not matching where they're valid (fixes #57).

### LINKED ISSUE #57: `where` clause, not highlighting correctly.
This is where the syntax should be highlighting `where` but doesn't ( based on this: https://github.com/rust-lang/rfcs/blob/master/text/0135-where.md definition ). (in short they can appear besides `impl`, `fn`, `trait`, `struct`.)

    impl Foo<A,B>
        where ...
    { }

    impl Foo<A,B> for C
        where ...
    { }

    impl Foo<A,B> for C
    {
        fn foo<A,B> -> C
            where ...
        { }
    }

    fn foo<A,B> -> C
        where ...
    { }

    struct Foo<A,B>
        where ...
    { }

    trait Foo<A,B> : C
        where ...
    { }

Ironically, currently `where` seems to highlight everywhere but in the only cases where it should be used.

### PR DESCRIPTION
**Pull request by TheEnigmaBlade**

### CODE REVIEW

**Comment by Alhadis** [comment]
Holy hell man, it's only been a week, [and you're already declaring this package dead](https://atom.io/packages/language-rust-redux)? Give @zargony a break, he could be on holiday for all we know.

**Comment by TheEnigmaBlade** [comment]
I'm not declaring it dead. I want to use a package that has all my fixes in it rather than a bunch of branches with different fixes. If he comes back and fixes a bunch, that's great!

I don't know why making a fork and having fun modifying and improving it requires such hostile behavior. Isn't that the point of open source software?

**Comment by Alhadis** [comment]
What's wrong with linking it to your packages directory with `apm link -d` or something similar?

**Comment by TheEnigmaBlade** [comment]
Because I know a couple other people who are interested, and it's the easiest method of distribution to them. If you don't want to use the package, feel free to ignore it.

**Comment by zargony** [comment]
Sorry for the delay. For some reason, I did not get mail notifications about these PRs and missed them.
Sadly, my main job does not include any Rust at the moment, so I don't get much time to spend on this project. I appreciate your help very much.
There's nothing wrong in forking this package if you get impatient. However, I'd also love to see you continue contributing your changes here. If you have time to work on it more often, I could as well share write access.

I just pushed a commit that introduces automated grammar testing on Travis-CI - something, I've wanted to add for a long time. This should make it easier to keep all highlighting working as intended (once the coverage grows).
Would you mind modifying your PRs to also include automated specs rather than manual test.rs snippets?

**Pull request merged**
